services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nines\DublinCoreBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Resources,Tests}'

    Nines\DublinCoreBundle\Controller\:
        resource: '../../Controller/*'
        public: true
        tags: ['controller.service_arguments']

    Nines\DublinCoreBundle\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: dcMenu, alias: dc}
