services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Nines\UtilBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Resources,Tests}'
