parameters:
    nines_text.trim_length: 50

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Nines\UtilBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Resources,Tests}'

    Nines\UtilBundle\EventListener\ContentExcerptListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    Nines\UtilBundle\EventListener\TermNameListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    Nines\UtilBundle\Services\Text:
        arguments:
            $defaultTrimLength: '%nines_text.trim_length%'

    Nines\UtilBundle\Twig\TextExtension:
        tags:
            - { name : twig.extension }
