services:
    nines.util.text:
        class: Nines\UtilBundle\Services\Text
        calls:
            - [ setLogger, ["@monolog.logger"]]

    nines.util.title_caser:
        class: Nines\UtilBundle\Services\TitleCaser
        calls:
            - [ setLogger, ["@monolog.logger"]]
            
    # provides class_name() and short_name() to get the full and short 
    # class name of an object.
    nines.util.twig:
        class: Nines\UtilBundle\Extensions\Twig\TwigExtension
        tags: 
            - { name: twig.extension }
