services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nines\UtilBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Resources,Tests}'
