services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        
    Nines\UserBundle\:
        resource: '../../*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../{Entity,Repository,Resources,Tests}'

    Nines\UserBundle\Menu\Builder:
        tags:
        - { name: knp_menu.menu_builder, method: userNavMenu, alias: user}
