parameters:
    # comment notifications
    nines_feedback.sender: ~
    nines_feedback.recipient: ~
    nines_feedback.subject: New feedback received

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nines\FeedbackBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Resources,Tests}'

    Nines\FeedbackBundle\Controller\:
        resource: '../../Controller/*'
        public: true
        tags:
            - 'controller.service_arguments'
            - 'knp_paginator.injectable'

    Nines\FeedbackBundle\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: navMenu, alias: nines_feedback}

    Nines\FeedbackBundle\Services\NotifierService:
        arguments:
            $sender: '%nines_feedback.sender%'
            $recipients: '%nines_feedback.recipients%'
            $subject: '%nines_feedback.subject%'

    Nines\FeedbackBundle\Services\CommentService:
        arguments:
            $routing: "%nines_feedback.routing%"
            $defaultStatusName: "%nines_feedback.default_status%"
            $publicStatusName: "%nines_feedback.public_status%"
        calls:
            - [ setAuthorizationChecker, ['@security.authorization_checker']]
            - [ setDoctrine, ["@doctrine"]]
            - [ setLogger, ["@monolog.logger"]]
            - [ setRouter, ["@router"]]
            - [ setFormFactory, ["@form.factory"]]
