services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nines\FeedbackBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Resources,Tests}'

    Nines\FeedbackBundle\Controller\:
        resource: '../../Controller/*'
        public: true
        tags: ['controller.service_arguments']

    Nines\FeedbackBundle\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: navMenu, alias: feedback}

    Nines\FeedbackBundle\Services\NotifierService:
        arguments:
            $sender: '%nines_feedback.sender%'
            $recipient: '%nines_feedback.recipient%'
            $subject: '%nines_feedback.subject%'
            $service: '@feedback.comment'
            
    feedback.comment:
        class: Nines\FeedbackBundle\Services\CommentService
        public: true
        arguments:
            $routing: "%nines_feedback.routing%"
            $defaultStatusName: "%nines_feedback.default_status%"
            $publicStatusName: "%nines_feedback.public_status%"
        calls:
            - [ setAuthorizationChecker, ['@security.authorization_checker']]
            - [ setDoctrine, ["@doctrine"]]
            - [ setLogger, ["@monolog.logger"]]
            - [ setRouter, ["@router"]]
            - [ setFormFactory, ["@form.factory"]]
