services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nines\BlogBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Resources,Tests}'

    Nines\BlogBundle\Controller\:
        resource: '../../Controller/*'
        public: true
        tags: ['controller.service_arguments']

    Nines\BlogBundle\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: postNavMenu, alias: posts}
            - { name: knp_menu.menu_builder, method: pageNavMenu, alias: pages}
